#ifndef __DEF_FOR_BALL_H__
#define __DEF_FOR_BALL_H__

#define BALL_COLLISION_BITMASK 0x000001
#define BALL_DENSITY 2.5
#define BALL_RESTITUTION 2.0
#define BALL_FRICTION 0.0

#define ANGLE_180_DEGREES 180
#define ANGLE_90_DEGREES 90

#define IMPULSE_VECTOR_SCALE_RATIO 0.01
#define IMPULSE_VECTOR_RATIO 50000
#define IMPULSE_VECTOR_MAX_SCALE 0.25
#define MAX_IMPULSE 100,100

#endif // __DEF_FOR_BALL_H__
