#ifndef __DEF_FOR_PLANKS_H__
#define __DEF_FOR_PLANKS_H__

#define PLANK_COLLITION_BITMASK 0x000002

#define WOODEN_PLANK_DENSITY 0.1
#define WOODEN_PLANK_RESTITUTION 0.1
#define WOODEN_PLANK_FRICTION 0.1

#define METAL_PLANK_DENSITY 0
#define METAL_PLANK_RESTITUTION 0
#define METAL_PLANK_FRICTION 0

#define RUBBER_PLANK_DENSITY 0.1
#define RUBBER_PLANK_RESTITUTION 0.1
#define RUBBER_PLANK_FRICTION 0.1

#define PLANK_ROTATE_TIME 0

#define SMALL_PLANK 0.5
#define NORMAL_PLANK 1
#define BIG_PLANK 1.5

#define RUBBER_PLANK_COST 3
#define METALL_PLANK_COST 2
#define WOODEN_PLANK_COST 1

#define WOODEN_PLANK "woddy plank.png"
#define METAL_PLANK "metal plank.png"
#define RUBBER_PLANK "rubber plank.png"

#define DESIGNATION_PLANK 'p'

#endif // __DEF_FOR_PLANKS_H__
