#ifndef __DEF_FOR_STAR_H__
#define __DEF_FOR_STAR_H__

#define STAR_COLLISION_BITMASK 0x000009

#define STAR_PLANK_DENSITY 0
#define STAR_PLANK_RESTITUTION 0
#define STAR_PALNK_FRICTION 0

#endif // __DEF_FOR_STAR_H__