#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 1
#define TRANSITION_TIME 0.5

#define BALL_COLLISION_BITMASK 0x000001
#define BALL_DENSITY 0.1
#define BALL_RESTITUTION 0.1
#define BALL_FRICTION 0.1

#define TEMP_DEFIN 45


//#define PIPE_SPAWN_FREQUENCY 0.003
//
//#define PIPE_GAP 10
//#define UPPER_SCREEN_PIPE_THRESHOLD 0.65
//#define LOWER_SCREEN_PIPE_THRESHOLD 0.35
//
//#define PIPE_MOVEMENT_SPEED 0.01
//
//#define BIRD_COLLISION_BITMASK 0x000001
//#define OBSTACLE_COLLISION_BITMASK 0x000002
//#define POINT_COLLISION_BITMASK 0x000003
//
//#define BIRD_FALLING_SPEED 0.0025
//#define BIRD_FLYING_SPEED 0.00375
//#define BIRD_FLY_DURATION 0.25
//
//#define SCORE_FONT_SIZE 0.1

#endif